# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Dropbox/Hobby/PRG/PyWork/vika_player/view/ui/bn_view_ui.ui'
#
# Created: Sun Oct 16 11:59:06 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ButtonView(object):
    def setupUi(self, ButtonView):
        ButtonView.setObjectName("ButtonView")
        ButtonView.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ButtonView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_bn = QtWidgets.QFrame(self.centralwidget)
        self.frame_bn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bn.setObjectName("frame_bn")
        self.frame_bn_layout = QtWidgets.QGridLayout(self.frame_bn)
        self.frame_bn_layout.setSpacing(10)
        self.frame_bn_layout.setContentsMargins(20, 20, 20, 20)
        self.frame_bn_layout.setObjectName("frame_bn_layout")
        self.bn_2 = QtWidgets.QToolButton(self.frame_bn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_2.sizePolicy().hasHeightForWidth())
        self.bn_2.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../files/gusi.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_2.setIcon(icon)
        self.bn_2.setIconSize(QtCore.QSize(240, 240))
        self.bn_2.setObjectName("bn_2")
        self.frame_bn_layout.addWidget(self.bn_2, 2, 1, 1, 1)
        self.bn_1 = QtWidgets.QToolButton(self.frame_bn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_1.sizePolicy().hasHeightForWidth())
        self.bn_1.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../files/antoshka.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_1.setIcon(icon1)
        self.bn_1.setIconSize(QtCore.QSize(240, 240))
        self.bn_1.setObjectName("bn_1")
        self.frame_bn_layout.addWidget(self.bn_1, 2, 0, 1, 1)
        self.bn_3 = QtWidgets.QToolButton(self.frame_bn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_3.sizePolicy().hasHeightForWidth())
        self.bn_3.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../files/kolobok.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_3.setIcon(icon2)
        self.bn_3.setIconSize(QtCore.QSize(240, 240))
        self.bn_3.setObjectName("bn_3")
        self.frame_bn_layout.addWidget(self.bn_3, 3, 0, 1, 1)
        self.bn_4 = QtWidgets.QToolButton(self.frame_bn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_4.sizePolicy().hasHeightForWidth())
        self.bn_4.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../files/bm.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_4.setIcon(icon3)
        self.bn_4.setIconSize(QtCore.QSize(240, 240))
        self.bn_4.setObjectName("bn_4")
        self.frame_bn_layout.addWidget(self.bn_4, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_bn)
        self.frame_player = QtWidgets.QFrame(self.centralwidget)
        self.frame_player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player.setObjectName("frame_player")
        self.frame_player_layout = QtWidgets.QVBoxLayout(self.frame_player)
        self.frame_player_layout.setSpacing(0)
        self.frame_player_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_player_layout.setObjectName("frame_player_layout")
        self.verticalLayout.addWidget(self.frame_player)
        ButtonView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ButtonView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ButtonView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ButtonView)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        ButtonView.setStatusBar(self.statusbar)

        self.retranslateUi(ButtonView)
        QtCore.QMetaObject.connectSlotsByName(ButtonView)

    def retranslateUi(self, ButtonView):
        _translate = QtCore.QCoreApplication.translate
        ButtonView.setWindowTitle(_translate("ButtonView", "MainWindow"))
        self.bn_2.setText(_translate("ButtonView", "Два веселых гуся"))
        self.bn_1.setText(_translate("ButtonView", "Антошка"))
        self.bn_3.setText(_translate("ButtonView", "Колобок"))
        self.bn_4.setText(_translate("ButtonView", "Бременские музыканты"))

